"""CG2D_EX0: model/src/cg2d_ex0.F @63cdc0b, the disconnected-tile (no EXCH) CG2D (vermix lane, M3 Task 30), and
FILL_HALO_LOCAL_RL of exch0_rl.F (generated by genmake2 from eesupp/src/exch0_rx.template)."""

import jax.numpy as jnp
from jax import lax

from mitjax.eesupp.global_sum import tile_sum_fortran
from mitjax.farray import FArray, loop_i, loop_j
from mitjax.model.src.cg2d import EXCH_S3D_RL, EXCH_XY_RL
from mitjax.model.src.cg2d_h import debLevZero
from mitjax.ops.fortran_minmax import MAX, MIN
from mitjax.ops.safe import safe_div


def fill_halo_local_rl(locFld, myOLw, myOLe, myOLs, myOLn, cornerMode_update=False):
    """FILL_HALO_LOCAL_RL( locFld, myOLw, myOLe, myOLs, myOLn, myNr, cornerMode, bi, bj, myThid )
    @63cdc0b exch0_rl.F (eesupp/src/exch0_rx.template, #ifdef DISCONNECTED_TILES)

    C     | SUBROUTINE FILL_HALO_LOCAL_RL
    C     | o Fill the halo region of a tile with its own interior values (periodic in the tile)

    locFld: an FArray (1-myOLw:sNx+myOLe, 1-myOLs:sNy+myOLn) (myNr = 1); every tile alone (the bi,bj loop is
    implicit). cornerMode: EXCH_IGNORE_CORNERS (False: the i fill runs on j = 1..sNy, the j fill on i = 1..sNx) or
    EXCH_UPDATE_CORNERS (True: the whole width). The three arms of each direction (sNx.EQ.1, sNx.LT.myOLw, else) are
    static (SIZE.h); within an arm the statements run in the Fortran order (the j fill reads what the i fill wrote)."""
    (_, ilo, ihi), (_, jlo, jhi) = locFld.dims
    sNx, sNy = ihi - myOLe, jhi - myOLn
    if cornerMode_update:
        iMin, iMax, jMin, jMax = 1 - myOLw, sNx + myOLe, 1 - myOLs, sNy + myOLn
    else:
        iMin, iMax, jMin, jMax = 1, sNx, 1, sNy
    j = loop_j(jMin, jMax)
    if sNx == 1:
        for ii in range(1 - myOLw, sNx + myOLe + 1):
            locFld = locFld.at[ii, j].set(locFld[1, j])                     # locFld(i,j,k) = locFld(1,j,k)
    else:
        for ii in (range(0, -myOLw, -1) if sNx < myOLw else range(1 - myOLw, 1)):
            locFld = locFld.at[ii, j].set(locFld[ii + sNx, j])              # locFld(i,j,k) = locFld(i+sNx,j,k)
        for ii in range(1, myOLe + 1):
            locFld = locFld.at[ii + sNx, j].set(locFld[ii, j])              # locFld(i+sNx,j,k) = locFld(i,j,k)
    i = loop_i(iMin, iMax)
    if sNy == 1:
        for jj in range(1 - myOLs, sNy + myOLn + 1):
            locFld = locFld.at[i, jj].set(locFld[i, 1])                     # locFld(i,j,k) = locFld(i,1,k)
    else:
        for jj in (range(0, -myOLs, -1) if sNy < myOLs else range(1 - myOLs, 1)):
            locFld = locFld.at[i, jj].set(locFld[i, jj + sNy])
        for jj in range(1, myOLn + 1):
            locFld = locFld.at[i, jj + sNy].set(locFld[i, jj])
    return locFld


def _tile_chain(op, init, vals, p):
    """`m = init; DO bj; DO bi: m = OP( vals(bi,bj), m )` with the site's winner p (Python loop over the tiles in
    tile order; one process: the following _GLOBAL_MAX_RL is the identity, eesupp/src/global_max.F)."""
    m = init
    for t in range(vals.shape[0]):
        m = op(vals[t], m, p=p)
    return m


def cg2d_ex0(cg2d_b, cg2d_x, numIters, nIterMin, *, cfg, cg2dh, params, ex):
    """CG2D_EX0( cg2d_b, cg2d_x, firstResidual, minResidualSq, lastResidual, numIters, nIterMin, myThid )
    @63cdc0b model/src/cg2d_ex0.F:13-371

    C     | SUBROUTINE CG2D_EX0
    C     | o Two-dimensional grid problem conjugate-gradient inverter
    C     |   (with preconditioner).
    C     | Note: this version is for DISCONNECTED_TILES: no EXCH, each tile solved on its own

    The arguments and returns of `mitjax.model.src.cg2d.cg2d` (same order; numIters, nIterMin static ints;
    `printed` = {"sumRHS", "rhsMax"} of the line :195-196). Per-tile quantities (errTile, eta_qrNtile, alphaTile,
    rhsNorm, minResTile, minResIter, actualIts, eta_qrNM1) are [tile] arrays; the tile IFs (:209, :287-288, :321)
    are selects per tile. The iteration DO it2d=1,numIters (:203-311) is a `lax.while_loop` that stops once
    err_sq < cg2dTolerance_sq (:204: every later iteration does nothing). The running MAX/MIN over the tiles are
    chains in tile order with the oracle's winners (vermix table: :117 "b", :130 "a", :181 "a", :182 "a", :305 "a",
    :356 "b"); _GLOBAL_MAX_RL is the identity for the oracle's single process. The INTEGER MIN/MAX of :354-355 are
    exact. Raise: printResidualFreq >= 1 with debugLevel >= debLevZero (:279-286 per-iteration print).
    Derivative: none (forward solver; SOLVE_FOR_PRESSURE's implicit-rule wiring is for CG2D only) -- a gradient
    through it raises in reverse mode (lax.while_loop)."""
    if params.debugLevel >= debLevZero and params.printResidualFreq >= 1:
        raise NotImplementedError("CG2D_EX0: printResidualFreq >= 1 (the per-iteration print :279-286) is not ported")
    sz = cfg.size
    sNx, sNy = sz.sNx, sz.sNy
    aW2d, aS2d, aC2d = cg2dh.aW2d, cg2dh.aS2d, cg2dh.aC2d
    pW, pS, pC = cg2dh.pW, cg2dh.pS, cg2dh.pC
    cg2dNorm, tol = cg2dh.cg2dNorm, cg2dh.cg2dTolerance_sq
    dt = cg2d_x.dtype
    nt = cg2d_x.ntiles
    j = loop_j(1, sNy)
    i = loop_i(1, sNx)
    T3 = lambda v: v[:, None, None]                                             # noqa: E731 [tile] -> [tile,1,1]
    # :94-97 local work arrays (NaN until written)
    cg2d_min = FArray(jnp.full((nt, sNy, sNx), jnp.nan, dt), "cg2d_min", i=(1, sNx), j=(1, sNy))
    cg2d_q = FArray(jnp.full((nt, sNy, sNx), jnp.nan, dt), "cg2d_q", i=(1, sNx), j=(1, sNy))
    cg2d_r = FArray(jnp.full((nt, sNy + 2, sNx + 2), jnp.nan, dt), "cg2d_r", i=(0, sNx + 1), j=(0, sNy + 1))
    cg2d_s = FArray(jnp.full((nt, sNy + 2, sNx + 2), jnp.nan, dt), "cg2d_s", i=(0, sNx + 1), j=(0, sNy + 1))

    # :105-133 normalise RHS (per tile)
    actualIts = jnp.zeros((nt,), jnp.int32)                                     # :109
    minResIter = jnp.zeros((nt,), jnp.int32)                                    # :110
    minResTile = jnp.full((nt,), -1.0, dt)                                      # :111  -1. _d 0
    eta_qrNM1 = jnp.full((nt,), 1.0, dt)                                        # :112  1. _d 0
    cg2d_b = cg2d_b.at[i, j].set(cg2d_b[i, j]*cg2dNorm)                         # :116
    absb = jnp.abs(cg2d_b[i, j]).reshape(nt, -1)                                # DO j; DO i (C order: i fastest)
    rhsMaxLoc = jnp.zeros((nt,), dt)                                            # :113  0. _d 0
    for n in range(absb.shape[1]):                                              # :114-119
        rhsMaxLoc = MAX(absb[:, n], rhsMaxLoc, p="b")                           # :117
    rhsNorm = jnp.where(rhsMaxLoc != 0., safe_div(1.0, rhsMaxLoc, rhsMaxLoc != 0.), 1.0)   # :120-121
    if cg2dh.cg2dNormaliseRHS:                                                  # :122-129
        cg2d_b = cg2d_b.at[i, j].set(cg2d_b[i, j]*T3(rhsNorm))                  # :125
        cg2d_x = cg2d_x.at[i, j].set(cg2d_x[i, j]*T3(rhsNorm))                  # :126
    rhsMax = _tile_chain(MAX, jnp.asarray(0.0, dt), rhsMaxLoc, "a")             # :105, :130 (:134 identity)
    cg2d_x = EXCH_XY_RL(cg2d_x, ex=ex)                                          # :137

    # :140-189 initial residual
    j1 = loop_j(0, sNy + 1)                                                     # :145-150
    i1 = loop_i(0, sNx + 1)
    cg2d_r = cg2d_r.at[i1, j1].set(0.)
    cg2d_s = cg2d_s.at[i1, j1].set(0.)
    if nIterMin >= 0:                                                           # :151-158
        cg2d_min = cg2d_min.at[i, j].set(cg2d_x[i, j])
    cg2d_r = cg2d_r.at[i, j].set(cg2d_b[i, j] -
                                 (aW2d[i, j]*cg2d_x[i-1, j]
                                  + aW2d[i+1, j]*cg2d_x[i+1, j]
                                  + aS2d[i, j]*cg2d_x[i, j-1]
                                  + aS2d[i, j+1]*cg2d_x[i, j+1]
                                  + aC2d[i, j]*cg2d_x[i, j]
                                  ))                                            # :166-172
    errTile = tile_sum_fortran(cg2d_r[i, j]*cg2d_r[i, j])                       # :160, :173-174
    sumRHStile = tile_sum_fortran(cg2d_b[i, j])                                 # :159, :175
    if nIterMin >= 0:                                                           # :178-180
        minResTile = errTile
    err_sq = _tile_chain(MAX, jnp.asarray(0.0, dt), errTile, "a")               # :140, :181
    sumRHS = _tile_chain(MAX, jnp.asarray(0.0, dt), jnp.abs(sumRHStile), "a")   # :141, :182
    cg2d_r = EXCH_S3D_RL(cg2d_r, 1, ex=ex)                                      # :186 (:187-188 identity)
    firstResidual = jnp.sqrt(err_sq)                                            # :189

    # :203-311  DO it2d=1, numIters: IF ( err_sq.GE.cg2dTolerance_sq )
    def cond(c):
        return (c[0] <= numIters) & (c[1] >= tol)

    def body(c):
        (it2d, err_sq, cg2d_x, cg2d_r, cg2d_s, cg2d_q, cg2d_min, errTile, eta_qrNM1, actualIts, minResTile,
         minResIter) = c
        act = errTile >= tol                                                    # :209
        a3 = T3(act)
        q = cg2d_q.at[i, j].set(pC[i, j]*cg2d_r[i, j]                           # :219-224
                                + pW[i, j]*cg2d_r[i-1, j]
                                + pW[i+1, j]*cg2d_r[i+1, j]
                                + pS[i, j]*cg2d_r[i, j-1]
                                + pS[i, j+1]*cg2d_r[i, j+1])
        eta_qrNtile = tile_sum_fortran(q[i, j]*cg2d_r[i, j])                    # :213, :225-226
        cgBeta = eta_qrNtile/eta_qrNM1                                          # :230
        s = cg2d_s.at[i, j].set(q[i, j]                                         # :235-236
                                + T3(cgBeta)*cg2d_s[i, j])
        s = fill_halo_local_rl(s, 1, 1, 1, 1)                                   # :241-244 EXCH_IGNORE_CORNERS
        q = q.at[i, j].set(aW2d[i, j]*s[i-1, j]                                 # :254-259
                           + aW2d[i+1, j]*s[i+1, j]
                           + aS2d[i, j]*s[i, j-1]
                           + aS2d[i, j+1]*s[i, j+1]
                           + aC2d[i, j]*s[i, j])
        alphaTile = tile_sum_fortran(s[i, j]*q[i, j])                           # :248, :260-261
        alpha = eta_qrNtile/alphaTile                                           # :264
        x = cg2d_x.at[i, j].set(cg2d_x[i, j]+T3(alpha)*s[i, j])                 # :271
        r = cg2d_r.at[i, j].set(cg2d_r[i, j]-T3(alpha)*q[i, j])                 # :272
        eT = tile_sum_fortran(r[i, j]*r[i, j])                                  # :268, :273-274
        newmin = (eT >= tol) & (eT < minResTile)                                # :287-288
        mn = cg2d_min.at[i, j].set(jnp.where(T3(newmin), x[i, j], cg2d_min[i, j]))   # :292-296
        r = fill_halo_local_rl(r, 1, 1, 1, 1)                                   # :299-302
        # the tile's IF (:209-304): inactive tiles keep every value
        sel = lambda new, old: FArray(jnp.where(a3, new.data, old.data), old.name, tiled=old.tiled,   # noqa: E731
                                      _dims=old.dims)
        cg2d_x, cg2d_r, cg2d_s, cg2d_q = sel(x, cg2d_x), sel(r, cg2d_r), sel(s, cg2d_s), sel(q, cg2d_q)
        cg2d_min = sel(mn, cg2d_min)
        eta_qrNM1 = jnp.where(act, eta_qrNtile, eta_qrNM1)                      # :231
        errTile = jnp.where(act, eT, errTile)
        actualIts = jnp.where(act, it2d, actualIts)                             # :277
        minResTile = jnp.where(act & newmin, eT, minResTile)                    # :290
        minResIter = jnp.where(act & newmin, it2d, minResIter)                  # :291
        err_sq = _tile_chain(MAX, jnp.asarray(0.0, dt), errTile, "a")           # :205, :305
        return (it2d + 1, err_sq, cg2d_x, cg2d_r, cg2d_s, cg2d_q, cg2d_min, errTile, eta_qrNM1, actualIts,
                minResTile, minResIter)

    c = (jnp.asarray(1, jnp.int32), err_sq, cg2d_x, cg2d_r, cg2d_s, cg2d_q, cg2d_min, errTile, eta_qrNM1, actualIts,
         minResTile, minResIter)
    (_, err_sq, cg2d_x, cg2d_r, cg2d_s, cg2d_q, cg2d_min, errTile, eta_qrNM1, actualIts, minResTile,
     minResIter) = lax.while_loop(cond, body, c)

    if nIterMin >= 0:                                                           # :315-330
        use = T3(errTile > minResTile)                                          # :321
        cg2d_x = cg2d_x.at[i, j].set(jnp.where(use, cg2d_min[i, j], cg2d_x[i, j]))   # :324
    if cg2dh.cg2dNormaliseRHS:                                                  # :332-343
        cg2d_x = cg2d_x.at[i, j].set(cg2d_x[i, j]/T3(rhsNorm))                  # :338
    # :348 _GLOBAL_MAX_RL( err_sq ): identity
    nIterMin_o = jnp.asarray(numIters, jnp.int32)                               # :349
    numIters_o = jnp.asarray(0, jnp.int32)                                      # :350
    minResidualSq = err_sq                                                      # :351
    for t in range(nt):                                                         # :352-358
        nIterMin_o = jnp.minimum(actualIts[t], nIterMin_o)                      # :354  MINMAX-RAW: INTEGER MIN
        numIters_o = jnp.maximum(actualIts[t], numIters_o)                      # :355  MINMAX-RAW: INTEGER MAX
        minResidualSq = MIN(errTile[t], minResidualSq, p="b")                   # :356
    lastResidual = jnp.sqrt(err_sq)                                             # :359
    # :360-368: alpha = -nIterMin; _GLOBAL_MAX_RL; nIterMin = NINT(-alpha) (and numIters, minResidualSq): the
    # identity for one process (the INTEGER -> REAL*8 -> NINT round trip is exact)
    printed = {"sumRHS": sumRHS, "rhsMax": rhsMax}
    return cg2d_b, cg2d_x, firstResidual, minResidualSq, lastResidual, numIters_o, nIterMin_o, printed
