"""Write probe.F: the gfortran program whose output is the oracle of mitjax/io/fortran_format.py (plan Task 11, lane MON).

    python mitjax/tests/fortran_format/make_probe.py        (re)write probe.F next to this file
    build + run (login node, seconds; the oracle's compiler and flags, reference/build.sh:92 and the Makefile of
    $MJX_REFERENCE/bin/*-f48c062):
        module load gcc/11.2.0-gcc-11.2.0
        gfortran -fallow-argument-mismatch -fconvert=big-endian -fimplicit-none -mcmodel=medium -Wall \
            -Wno-unused-dummy-argument -ffp-contract=off -O0 -ffixed-line-length-132 probe.F -o probe
        ./probe > probe_gfortran11.out

The program reads every value from an INTEGER*8 bit pattern (TRANSFER, no literal conversion by the compiler), writes
it with every edit descriptor MITgcm's monitor and solver printouts use (and a few neighbours), and prints one line per
(value, format): `F <format id> <bits as Z16.16> |<field>|`. Integers: `I <format id> <value> |<field>|`. A second
part probes gfortran's MIN/MAX intrinsics on signed zeros and NaN (operands from an array, so that nothing is folded at
compile time): `M <op> <bits a> <bits b> <bits result>`.
"""

import math
import struct
from pathlib import Path

HERE = Path(__file__).resolve().parent


def bits(x):
    return struct.unpack(">q", struct.pack(">d", x))[0]


NAN, PINF = float("nan"), float("inf")
VALUES = [
    0.0, -0.0, 1.0, -1.0, 0.1, -0.1, 1.0 / 3.0, 2.0 / 3.0, 0.5, 1.5, 2.5, 10.0, 100.0, 1.0e-5, 2.5e-5,
    36000.0, 3.1104e9, 3.1104864e9, 9.6840090317157e-01, -1.6623523877581e+00, 1.3226782657554e+18,
    0.99999999999995, 0.999999999999949, 0.999999999999951, 9.99999999999995, 9.9999999999999949e99,
    9.99999999999996e99, 1.0e99, 1.0e100, -1.0e100, 1.2345e107, 2.0962566239063e-116, 1.0e-99, 1.0e-100,
    9.99999999999996e-100, 1.0e300, -1.0e300, 1.7976931348623157e308, 2.2250738585072014e-308,
    2.2250738585072009e-308, 1.0e-310, -1.0e-310, 4.9406564584124654e-324, -4.9406564584124654e-324,
    # ties at the 14th significant digit (exactly representable: 15-digit integers < 2**53)
    100000000000005.0, 100000000000015.0, 100000000000025.0, -100000000000005.0, 123456789012345.0,
    # ties at the 4th significant digit (E11.3) and at the 8th/9th (E15.8)
    1.0005, 1.0015, 1.0625, 1.1875, 12345.5, 123456785.0, 123456795.0,
    math.pi, -math.e, 6.02214076e23, 1.602176634e-19, 8.6400e4, 1.0e10, 9.81, 1035.0,
]
SPECIAL = [NAN, -NAN, PINF, -PINF]
FORMATS = ["(1X,1P1E21.13)", "(1PE23.14)", "(1PE11.3)", "(1P2E11.3)", "(E15.8)", "(1PE15.8)", "(ES21.13)",
           "(1PE22.13E3)", "(E21.13E3)", "(F12.4)", "(F20.10)", "(0PF8.2)", "(1PE12.4E3)"]
INTS = [0, 1, -1, 7, 36000, 36010, 123456789, 2147483647, -2147483648, -36000]
IFORMATS = ["(1X,I21)", "(I10)", "(I4.4)", "(I21)", "(I3)"]
# F formats are probed on moderate values only (no special rule needed for them in the monitor port)
F_MAX = 1.0e6
MINMAX = [(0.0, -0.0), (-0.0, 0.0), (0.0, 0.0), (-0.0, -0.0), (1.0, NAN), (NAN, 1.0), (-1.0, NAN), (NAN, -1.0),
          (NAN, NAN), (1.0, 2.0), (2.0, 1.0), (-0.0, 1.0), (1.0, -0.0)]


def fortran_source():
    vals = VALUES + SPECIAL
    nv, nf, ni, nm = len(vals), len(FORMATS), len(INTS), len(MINMAX)
    L = []
    a = L.append
    a("C     Generated by mitjax/tests/fortran_format/make_probe.py; do not edit.")
    a("      PROGRAM PROBE")
    a("      IMPLICIT NONE")
    a(f"      INTEGER NV, NF, NI, NM")
    a(f"      PARAMETER ( NV = {nv}, NF = {nf}, NI = {ni}, NM = {nm} )")
    a("      INTEGER*8 VB(NV), MA(NM), MB(NM)")
    a("      INTEGER IV(NI)")
    a("      REAL*8 X, Y, Z, XA(NM), XB(NM)")
    a("      LOGICAL FOK(NV)")
    a("      CHARACTER*80 FIELD")
    a("      INTEGER N, IL")
    for n, v in enumerate(vals, 1):
        a(f"      VB({n}) = INT(Z'{bits(v) & 0xFFFFFFFFFFFFFFFF:016X}', 8)")
        ok = math.isfinite(v) and abs(v) < F_MAX
        a(f"      FOK({n}) = .{'TRUE' if ok else 'FALSE'}.")
    for n, v in enumerate(INTS, 1):
        a(f"      IV({n}) = {v}" if v != -2147483648 else f"      IV({n}) = -2147483647 - 1")
    for n, (x, y) in enumerate(MINMAX, 1):
        a(f"      MA({n}) = INT(Z'{bits(x) & 0xFFFFFFFFFFFFFFFF:016X}', 8)")
        a(f"      MB({n}) = INT(Z'{bits(y) & 0xFFFFFFFFFFFFFFFF:016X}', 8)")
    a("      DO N = 1, NV")
    a("       X = TRANSFER( VB(N), X )")
    for f, fmt in enumerate(FORMATS, 1):
        if fmt.startswith("(F") or fmt.startswith("(0PF"):
            a("       IF ( FOK(N) ) THEN")
            ind = " "
        else:
            ind = ""
        a(f"      {ind} FIELD = ' '")
        if fmt == "(1P2E11.3)":
            a(f"      {ind} WRITE(FIELD,'{fmt}') X, -X")
        else:
            a(f"      {ind} WRITE(FIELD,'{fmt}') X")
        a(f"      {ind} IL = LEN_TRIM(FIELD)")
        a(f"      {ind} WRITE(*,'(A,I3,1X,Z16.16,A,A,A)') 'F', {f}, VB(N), ' |', FIELD(1:IL), '|'")
        if ind:
            a("       ENDIF")
    a("      ENDDO")
    a("      DO N = 1, NI")
    for f, fmt in enumerate(IFORMATS, 1):
        a("       FIELD = ' '")
        a(f"       WRITE(FIELD,'{fmt}') IV(N)")
        a("       IL = LEN_TRIM(FIELD)")
        a(f"       WRITE(*,'(A,I3,1X,I12,A,A,A)') 'I', {f}, IV(N), ' |', FIELD(1:IL), '|'")
    a("      ENDDO")
    a("      DO N = 1, NM")
    a("       XA(N) = TRANSFER( MA(N), X )")
    a("       XB(N) = TRANSFER( MB(N), X )")
    a("      ENDDO")
    a("      DO N = 1, NM")
    a("       X = XA(N)")
    a("       Y = XB(N)")
    a("       Z = MIN(X,Y)")
    a("       WRITE(*,'(A,3(1X,Z16.16))') 'M MIN', X, Y, Z")
    a("       Z = MAX(X,Y)")
    a("       WRITE(*,'(A,3(1X,Z16.16))') 'M MAX', X, Y, Z")
    a("       Z = ABS(X)")
    a("       WRITE(*,'(A,3(1X,Z16.16))') 'M ABS', X, X, Z")
    a("      ENDDO")
    a("      END")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    (HERE / "probe.F").write_text(fortran_source())
    print(f"wrote {HERE / 'probe.F'}")
