"""Renders docs/YARDSTICK.md and docs/REFERENCE_RUNS.md from the registered oracle runs (plan Task 3b).

Called by `reference/reference_runs.py --docs`; scripts/tests/test_reference_runs.py renders again and requires the
committed files to be equal, so every number in the two documents is the value measured on the runs now. Stdlib only.
"""

import importlib.util
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
_spec = importlib.util.spec_from_file_location("_mjx_reference_runs_d", REPO / "reference" / "reference_runs.py")
rr = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(rr)
trj, cmp_runs = rr.trj, rr.cmp_runs

GEN = "<!-- generated by `python reference/reference_runs.py --docs`; edit reference/reference_docs.py, not this file -->"

# why a variable gives no comparison (`--`), per (experiment, input dir, name); checked against the files in render()
NOT_COMPARED = {
    ("advect_cs", "PS"): "momStepping=.FALSE.: no cg2d call, no `cg2d_init_res` line in our STDOUT nor in results/",
    ("advect_xy", "PS"): "momStepping=.FALSE.: no cg2d call, no `cg2d_init_res` line in our STDOUT nor in results/",
    ("advect_xz", "PS"): "momStepping=.FALSE.: no cg2d call, no `cg2d_init_res` line in our STDOUT nor in results/",
    # M3: global_ocean.90x40x15/input.idemix has its own data.pkg without useSBO (input/data.pkg sets it)
    **{("global_ocean.90x40x15", n): "useSBO is not set in input.idemix/data.pkg: no `%SBO` line in our STDOUT nor in "
       "results/output.idemix.txt" for n in ("sbo_M", "sboFW", "sboAc", "sboAp")},
}

PROPOSALS = """\
## Variables below 10 digits, or not compared: proposals for Nikolay (not decided)

**No compared check-list variable of any M1 variant is below 10 digits:** our gfortran `-O0` build of master
reaches 12 to 16 digits against `results/` everywhere (lowest: `advect_xz/input.pqm` Smn 12, Tmn 13; `advect_xy/input`
Tmn/Tmx 14; `advect_xz/input.nlfs` Smn/Smx/Ssd 14). The Task 2 hint (global_ocean.90x40x15 PS agreeing only to 10 digits
between checkpoints 65z and 67v) does not show here: our master build gives PS 16 digits against the current
`results/output.txt`.

Proposal 1 (forward acceptance per variant): JAX vs our own oracle's STDOUT >= 13 digits for every check-list
variable, or bitwise where the oracle comparison is bitwise; and JAX vs `results/` >= the yardstick digits of the table
above for every variable, not only the deciding one (testreport's verdict reads only the first variable and passes a
NaN in any other, Task 2).

Proposal 2 (roundoff-level variables): the second-tiling runs below show that some check-list variables are means of
fields whose value is at roundoff level (barotropic gyre Uav, Vav; baroclinic gyre Ssd, Vav; advect_xz Uav): changing
only the tile layout of the Fortran itself changes them by O(1) relative (0 digits) at a field-scale difference of
~1e-15. Our build reaches 16 digits on them against `results/` only because it sums in the reference's tile order.
For these variables require the JAX global sums in the Fortran tile and loop order (PORTING_RULES §4) and gate them at
the yardstick; if a JAX layout cannot sum in that order, compare them relative to the field scale (`<f>_max`) at the
1e-13 class instead of in testreport digits. Listed per variant in the invariance table ("0 digits" entries).

Variables testreport cannot compare (`--`) and what is proposed for each:
- `advect_xy` (both variants) and `advect_xz` (all three) **PS**: these experiments run with `momStepping=.FALSE.`,
  so neither our STDOUT nor `results/` has a `cg2d_init_res` line (testreport: "Not enough lines"). Proposal: JAX
  prints no `cg2d_init_res` line either (the same `--`); the deciding variable is Tsd (16 digits).
- `tutorial_global_oce_optim/input_ad` **admGrd** (testreport's deciding variable) is 0 digits by construction: the
  forward-only build prints the adjoint gradient it reads from the zero `adxx_qnet` file (option (i)), i.e. 0. It is
  not an oracle value; the TAF reference value comes only from `results/output_adm.txt`. Proposal: the JAX adjoint
  gradient is gated against `results/output_adm.txt` at >= 10 digits (plan Overview, unchanged), and against the
  oracle's FD gradient (admFwd) by the gradient trust protocol.
- `tutorial_global_oce_optim/input_ad` adm **T+ S+ U+ V+** (`dynstat_ad*`): `results/output_adm.txt` has no adjoint
  monitor lines and a forward-only build prints none; testreport gives `--` for the TAF build too. Proposal: no
  reference comparison in M1 (plan Task 16: self-consistency test only), as planned.
- `tutorial_global_oce_optim/input_ad` **admCst** and **admFwd**: 16 digits (every printed digit equal) with option (i);
  the forward-only build's forward `%MON` lines also agree with the forward lines of `results/output_adm.txt` to 16
  digits in every default-list variable.
"""


M2_PROPOSALS = """\
## M2: variables below 10 digits, or not compared: proposals for Nikolay (not decided)

Deciding variable: 16 digits in every M2 forward variant except `adjustment.cs-32x32x1` (PS 14 in both variants) and
`global_ocean.cs32x15/input.in_p` (PS 11); the code_ad variants: admCst and admFwd as tabled. Below 10 digits (all
roundoff-level means or standard deviations of nearly uniform or zero-mean fields, the class of M1's Proposal 2):
- `adjustment.cs-32x32x1/input` **Vav 4**: dynstat_vvel_mean is O(1e-19..1e-17) against dynstat_vvel_max O(0.3)
  (field-scale 1e-17); the first four blocks are bitwise, later ones differ from `results/` in the 5th digit of a
  roundoff value.
- `adjustment.cs-32x32x1/input.nlfs` **Tsd 0, Uav 0, Vav 0**: theta is uniform (300): its standard deviation is
  2.3e-13 here and 1.1e-13..2.3e-13 in `results/` (1e-15 of the field); the mean velocities are O(1e-18) of a field
  of O(0.1). The same quantities differ between tilings of M1's own oracle.
Proposal (as M1 Proposal 2): gate these variables relative to the field scale (max(|f_max|,|f_min|) of the same
record) at the 1e-13 class, and require the JAX global sums in the Fortran tile order so that the cube's
cross-face sums can be bitwise where the oracle is bitwise; every other variable at >= its yardstick digits.

Lowest compared digits >= 10 but low: `global_ocean.cs32x15/input.in_p` PS 11, Uav 12, Smn/Umn/Vmx/Vav/Vsd 13. This
variant runs sea ice, EXF and GGL90 (useSEAICE, useEXF, useGGL90 in its data.pkg): **proposal: move input.in_p to M4**
(sea ice) with the other cs32x15 sea-ice variants; its oracle runs and coverage exist already.

Forward-only code_ad variants (global_ocean.90x40x15/input_ad, .kapgm, .kapredi, .bottomdrag;
tutorial_tracer_adjsens/input_ad, .som81; session 7: global_ocean.cs32x15/input_ad): admCst and admFwd 16 digits in
all seven (the FD gradients of the zero-adxx runs equal the TAF build's FD lines of `results/output_adm*.txt` in
every printed digit), except admCst 14 for `tutorial_tracer_adjsens/input_ad.som81` (1.84096178634598E+14 here, ...599E+14 in `results/`: the TAF reference
cost comes from the adjoint build's forward sweep, our FD lines are 16), and the forward `%MON` lines 16 digits in
every default-list variable. The zero vs random adxx runs differ only in the `adjoint_gradient` lines (table below).
`global_ocean.cs32x15/input_ad` (lane A session 7): admCst 16, admFwd 16, forward lists 16 except PS `--`: its
`results/output_adm.txt` has 10 `cg2d_init_res` lines, the 5 of the forward sweep (equal to ours in every printed
digit) and 5 `CG2D_MAD: cg2d_init_res` lines printed by the adjoint solver in the reverse sweep (another TAF reference
for the JAX adjoint: the adjoint cg2d's initial residual per step); testreport's line count differs, so no comparison.

Not compared (`--`): `advect_cs` PS (momStepping=.FALSE., no cg2d line in our STDOUT nor in `results/`, as
advect_xy/xz in M1); the code_ad variants' admGrd (0 by construction of the forward-only build, as optim); their adm
T/S/U/V rows (`ad_dynstat_ad*`): unlike optim, `results/output_adm*.txt` of these seven variants HAS the TAF adjoint
monitor lines (table "TAF adjoint monitor lines" below), but a forward-only build prints none. Proposals: the JAX adjoint gradient against
`results/output_adm*.txt` at >= 10 digits (plan Overview) and against the oracle FD gradient by the trust protocol;
the JAX adjoint monitor (`%MON ad_dynstat_ad*`) against these TAF lines is the first reference comparison of it
(plan Task 16): digits recorded at the first measurement, threshold proposed then.
"""


M3_PROPOSALS = """\
## M3: variables below 10 digits, or not compared: proposals for Nikolay (not decided)

Deciding variable 16 digits in all 24 M3 variants; every compared variable 16 digits in front_relax (5),
ideal_2D_oce (2), tutorial_reentrant_channel, MLAdjust (7), global_ocean.90x40x15 input.dwnslp/input.idemix,
vermix/input, .ggl90, .gglLC. Lower ones, all in the 1-D vermix column:
- `vermix/input.my82`, `.opps`, `.pp81` **Ssd 1**: salt is uniform (35 everywhere, `dynstat_salt_max` = 35.0); its
  standard deviation is roundoff, 6e-15..3e-14 here and in `results/` (1e-15 of the field), the class of M1 Proposal 2.
- `vermix/input.my82` **Vmx 8**, `.pp81` **Vmx 9**: `dynstat_vvel_max` is O(1e-91..1e-85) (v is zero up to the first
  roundoff of a Coriolis term in a column forced only in x); the differing digits are noise on a value 1e85 below the
  u field. Further 10-14 digits in the same runs (Tmx 13, Umn/Umx 10, Usd/Vsd 10-11; input.dd Tmn/Tmx/Smx/Ssd 14,
  opps Umn 13) are against `results/` (another build); our plain, dumps-off and dumps-on runs agree in every printed
  digit (invisibility table).
Proposal (as M1 Proposal 2): gate the means and standard deviations relative to the field scale at the 1e-13 class,
and the extreme values of a field that is zero up to roundoff (vermix v) relative to the scale of the velocity field
(max |u|, |v|); every other variable at >= its yardstick digits.

Not compared (`--`): `global_ocean.90x40x15/input.idemix` sbo_M, sboFW, sboAc, sboAp (no useSBO in its data.pkg: no
`%SBO` line in our STDOUT nor in `results/output.idemix.txt`).
"""


M4_PROPOSALS = """\
## M4: variables below 10 digits, or not compared: proposals for Nikolay (not decided)

The table below is generated from the yardstick rows (every compared check-list variable of an M4 variant below 10
digits; admGrd of the forward-only code_ad builds excluded, 0 by construction as in M1/M2). Our plain, dumps-off and
dumps-on runs agree in every printed digit for all 31 M4 variants (invisibility table), so these are differences of
our gfortran -O0 build of master against `results/` (written on another platform), not of the instrumentation.
- `lab_sea/input.hb87` (adaptive EVP: data.seaice SEAICEaEVPcoeff=0.5, SEAICEnEVPstarSteps=500,
  useHB87stressCoupling=.TRUE.): PS, Uav, Vav at 4 digits, Usd and hSImx at 5, the other ocean and ice statistics at
  6-9, the lowest of any variant so far; every other lab_sea variant (LSR, free drift, salt plume) is 16 everywhere.
- `seaice_itd/input.thermo` (LSR with LSR_ERROR=1.E-12, SEAICElinearIterMax=1500, its data.seaice): the ice-velocity
  statistics uSI*/vSI* at 6-9 digits, aSIav/aSIsd 8, hSIsd 9 (input and input.lipscomb07: 12 and more).
Proposal: first repeat each of the two on a second platform build (or with -O0 vs the testreport `-ieee` flags compared
line by line over the run) before any acceptance number is set for them; until then their acceptance is our own
oracle (bitwise / >= 13 digits), not `results/`. Every other M4 variable is >= 10 digits (cs32x15 sea-ice variants:
PS 11, as in M2 `input`).

Not compared (`--`): PS of offline_exf_seaice and seaice_itd (the ocean is not stepped: no cg2d call, no
`cg2d_init_res` line in our STDOUT nor in `results/`), and the forward variables of the forward-only code_ad variants'
adm lists (as M2: the adjoint build's `results/output_adm*.txt` has no matching forward block; the forward list rows
compare them).
"""


def below10_section(variants, milestone):
    """Every compared check-list variable below 10 digits (admGrd of the code_ad builds excluded)."""
    out = [f"### {milestone}: compared variables below 10 digits", "", "| variant | variable | digits |",
           "|---|---|---:|"]
    for exp, inp, code in variants:
        ad = (exp, inp) in rr.AD_VARIANTS
        for r in rr.yardstick_rows(exp, inp):
            if r[0].startswith("forward list") or r[2] == 99 or r[2] >= 10 or (ad and r[1] == "admGrd"):
                continue
            out.append(f"| {_variant_label(exp, inp)} | {r[1]} | {r[2]} |")
    return out


def _digits_table(rows):
    out = ["| section | variable | grep pattern | digits | deciding | note |", "|---|---|---|---:|:---:|---|"]
    for section, name, d, dec, pat in rows:
        note = {16: "every printed digit equal", 22: "all values zero in both files", 99: "no comparison"}.get(d, "")
        out.append(f"| {section} | {name} | `{pat}` | {rr.fmt_digits(d)} | {'yes' if dec else ''} | {note} |")
    return out


def _variant_label(exp, inp):
    return f"{exp}/{inp}"


def yardstick_section(variants=None, heading="## Yardstick: our oracle's STDOUT vs `results/`"):
    lines = [heading, "",
             "| variant | runs (STDOUT) | deciding variable | its digits | lowest compared digits | not compared |",
             "|---|---|---|---:|---:|---|"]
    detail = []
    for exp, inp, code in rr.VARIANTS if variants is None else variants:
        rows = rr.yardstick_rows(exp, inp)
        main = [r for r in rows if not r[0].startswith("forward list")]
        dec = next((r for r in main if r[3]), None)
        ad = (exp, inp) in rr.AD_VARIANTS
        comp = [r[2] for r in main if r[2] != 99 and not (ad and r[1] == "admGrd")]
        nc = [r[1] for r in main if r[2] == 99]
        runs = "fdzero + yardstick" if ad else rr.find_run(exp, inp, "yardstick")["run_id"]
        lines.append(f"| {_variant_label(exp, inp)} | {runs} | {dec[1]} | {rr.fmt_digits(dec[2])} | "
                     f"{min(comp) if comp else '--'} | {' '.join(dict.fromkeys(nc)) or '-'} |")
        names = rr.checklist_names(exp, inp)
        detail += ["", f"### {_variant_label(exp, inp)}", "",
                   f"Check list ({len(names)} variables, testreport's listVar): {' '.join(names)}", ""]
        detail += _digits_table(rows)
        for name in dict.fromkeys(r[1] for r in main if r[2] == 99):
            why = NOT_COMPARED.get((exp, name))
            if why:
                detail.append(f"\n`{name}` not compared: {why}.")
    note = ["", "The lowest-digits column excludes admGrd of the forward-only code_ad builds (0 by construction, see "
            "the proposals). Every compared variable of the jaxdump runs (dumps off and on) and of the repeat runs has the "
            "same STDOUT numbers as the yardstick run (section 'Repeat and instrumented runs'; M2: the invisibility "
            "table)."]
    return lines + note + detail


def _first_numbers(res):
    """Short description of the numeric differences of a compare_runs result."""
    rec = res["records"]
    diff = [n for n in res["different"] if "only_in" not in rec[n]]
    only = [f"{n} only in {rec[n]['only_in']}" for n in res["different"] if "only_in" in rec[n]]
    return diff, only


def invariance_section():
    out = ["## Invariance checks", "",
           "### (a) Second tiling (same binary source, another SIZE.h; plan [P§5], [E§7])", "",
           "Each M1 code was rebuilt with one other tile layout (build tag `retile`, `reference/retile/<exp>-<code>/"
           "SIZE.h`, build job 27827362) and run (job 27827364). Every `SIZE.h_mpi` of the M1 codes has nPx*nPy > 1, "
           "i.e. needs MPI; per the dispatch the MPI tile shape is used in one process instead (nP -> nS) where it "
           "differs from SIZE.h (barotropic gyre, global_ocean), otherwise one tile for the whole domain. "
           "global_ocean's 7x5 tiles of 10x10 need its `data.exch2.mpi` (blankList=30): the run directory is "
           "testreport's MPI one (`make_rundir.py --mpi`, data.exch2.mpi linked as data.exch2) with a serial binary.",
           "", "Columns: check-list digits of the retiled run with the original run as the reference "
           "(testreport's comparison); `%MON`/`%SBO`/cg2d names that differ (of all names printed); the largest "
           "difference relative to the field scale among the `%MON dynstat_*`, `%SBO` and `cg2d_init_res` values "
           "(for `<f>_mean|_sd|_del2` the scale is max(|<f>_max|,|<f>_min|) of the same record, else the value "
           "itself); names printed in one tiling only. Means without a max/min record at roundoff level (e.g. "
           "`surfExpan_*_mean`, ~1e-17) change by O(1) relative; they are listed below but not in this column.", "",
           "| variant | tiling (base -> retile) | check-list digits retile vs base (< 16 only) | %MON/cg2d names "
           "differing | largest field-scale difference | printed in one tiling only |", "|---|---|---|---|---|---|"]
    tiling = {"tutorial_barotropic_gyre": "1 tile 62x62 -> 2x2 tiles 31x31",
              "tutorial_baroclinic_gyre": "2x2 tiles 31x31 -> 1 tile 62x62",
              "advect_xy": "1x2 tiles 20x10 -> 1 tile 20x20", "advect_xz": "2x1 tiles 10x1 -> 1 tile 20x1",
              "global_ocean.90x40x15": "9x4 tiles 10x10 (36, no data.exch2) -> 7x5 tiles 10x10 (35, blankList=30)",
              "tutorial_global_oce_optim": "2x2 tiles 45x20 -> 1 tile 90x40"}
    detail = []
    for exp, inp, code in rr.VARIANTS:
        base = rr.run_top(rr.find_run(exp, inp, "yardstick"))
        test = rr.run_top(rr.find_run(exp, inp, "retile"))
        trk = trj.KIND_FWD if (exp, inp) == rr.OPTIM else None
        res = cmp_runs.compare(base, test, "tiling", exp, inp, trk)
        diff, only = _first_numbers(res)
        low = [f"{n} {rr.fmt_digits(d)}" for n, d in res["checklist"] if d not in (16, 22)]
        dyn = [(res["records"][n]["scale_rel"], n) for n in diff
               if re.match(r"%MON dynstat_|cg2d_init_res|%SBO", n) and res["records"][n]["scale_rel"] is not None]
        big = max(dyn) if dyn else None
        out.append(f"| {_variant_label(exp, inp)} | {tiling[exp]} | {', '.join(low) or 'all 16 (22 for zeros)'} | "
                   f"{len(diff)} of {len(res['records'])} | "
                   f"{f'{big[0]:.1e} ({big[1]})' if big else '-'} | {'; '.join(only) or '-'} |")
        if diff:
            detail.append(f"- {_variant_label(exp, inp)}: " + ", ".join(
                f"{n} ({res['records'][n]['n_diff']}/{res['records'][n]['n'][0]} values, field-scale "
                f"{res['records'][n]['scale_rel']:.1e})" if res["records"][n]["scale_rel"] is not None
                else f"{n} (text)" for n in diff))
    out += ["", "Every differing name, with how many of its values differ and the largest field-scale difference:",
            ""] + detail
    out += ["", "Findings: the forward state is not bitwise tile-invariant in the Fortran itself (global sums in tile "
            "order: cg2d residuals, means and standard deviations, the area/volume-weighted statistics) except for "
            "advect_xy (bitwise in every printed number) and global_ocean, where every dynamics and SBO number is "
            "bitwise and only the grid statistics change (they average over all tiles, and the blank tile 30 is "
            "absent in the 35-tile layout). Field-scale differences stay at 1e-11 or below; the largest are the "
            "w-velocity statistics and cg2d_init_res (iterative solver). Which `%MON` lines exist depends on the tiling: "
            "`dynstat_sst`/`dynstat_sss` are printed only when nSx = nSy = 1 (pkg/monitor/monitor.F:121-130, 'print "
            "stats only if nSx=nSy=1 since otherwise stats are wrong'). So a JAX layout that differs from the "
            "experiment's SIZE.h cannot be expected to match the oracle bitwise in these statistics; the P=1 vs P=N "
            "bitwise gate (PORTING_RULES §4) holds the tile layout fixed and only changes the device count."]
    out += ["", "### (b) Output requests: diagnostics off, mnc off ([E§3])", "",
            "Overlays of `data.pkg` in a run directory of their own (`make_rundir.py --set`, job 27827363), compared "
            "with the yardstick run. Numeric records = every `%MON`, `%SBO`, `cg2d_*` line (compare_runs.py).", "",
            "| variant | overlay | numeric records | check-list digits vs base | STDOUT lines changed (exemptions: build "
            "stamp, timers) | written files |", "|---|---|---|---|---|---|"]
    for (exp, inp), labs in rr.OUTPUT_OFF.items():
        for lab in labs:
            base = rr.run_top(rr.find_run(exp, inp, "yardstick"))
            test = rr.run_top(rr.find_run(exp, inp, lab))
            res = cmp_runs.compare(base, test, "output", exp, inp)
            diff, only = _first_numbers(res)
            low = [f"{n} {d}" for n, d in res["checklist"] if d not in (16, 22, 99)]
            f = res["files"]
            out.append(f"| {_variant_label(exp, inp)} | {lab} | "
                       f"{'all identical' if not res['different'] else 'DIFFERENT: ' + ' '.join(res['different'])} "
                       f"({sum(r['n'][0] for r in res['records'].values())} values) | {', '.join(low) or 'all 16'} | "
                       f"{res['stdout']['changed_lines']} in {res['stdout']['hunks']} hunks | "
                       f"{f['common']} common ({len(f['differ'])} differ: {', '.join(f['differ']) or '-'}; "
                       f"{len(f['nc_stamp_only'])} netCDF equal but for the build stamp), "
                       f"{len(f['only_base'])} only base, {len(f['only_test'])} only overlay |")
    out += ["", "Findings: switching diagnostics or mnc off changes no number the model prints: the state is "
            "independent of these output requests in all M1 variants that use them. The STDOUT differences are the "
            "echo of the overlaid `data.pkg` line, the package status line, the package's own parameter print-out "
            "(data.diagnostics / data.mnc echo, diagnostics list) and its timer sections; the file differences are "
            "the diagnostics/mnc output files themselves (mnc off writes MDS files instead of netCDF), the overlaid "
            "data.pkg (a file instead of a link) and STDERR.0000, which gains the package's two warning lines "
            "('ignores \"data.diagnostics\" file since useDiagnostics= F', the same for data.mnc)."]
    return out


def repeat_section():
    out = ["## Repeat, instrumented and debugMode runs", "",
           "| variant | run | numeric records vs yardstick run | STDOUT lines changed (exemptions) | files |",
           "|---|---|---|---|---|"]
    for exp, inp, code in rr.VARIANTS:
        base = rr.run_top(rr.find_run(exp, inp, "yardstick"))
        for kind, ck in (("repeat", "tiling"), ("jdoff", "tiling"), ("debug", "debug")):
            run = rr.find_run(exp, inp, kind)
            res = cmp_runs.compare(base, rr.run_top(run), ck)
            f = res["files"]
            out.append(f"| {_variant_label(exp, inp)} | {run['run_id']} | "
                       f"{'identical' if not res['different'] else 'DIFFERENT: ' + ' '.join(res['different'][:5])} | "
                       f"{res['stdout']['changed_lines']} | {f['common']} common, {len(f['differ'])} differ "
                       f"(+{len(f['nc_stamp_only'])} netCDF build stamp only), "
                       f"{len(f['only_base'])}/{len(f['only_test'])} only base/run |")
    out += ["", "The repeat runs (same binary, another job) and the jaxdump binary with dumps off reproduce the "
            "yardstick run's STDOUT line for line (build stamps and timers exempted). The debugMode runs change no "
            "printed number; their STDOUT adds the DEBUG_MSG lines (exempted), the eedata echo, the `debugMode = T` "
            "parameter line, debugLevel 2 -> 4 where printed, and the extra I/O and field print-outs of the higher "
            "debugLevel; with the higher debugLevel the model also writes extra files (e.g. RhoRef.data). Call order "
            "per variant: `reference/call_order/<exp>-<input>.txt` (initialisation, time step 1, later steps "
            "compared with step 1: every later step has the same call sequence in all nine variants)."]
    return out


def fd_section():
    zero = rr.run_top(rr.find_run(*rr.OPTIM, "fdzero"))
    rnd = rr.run_top(rr.find_run(*rr.OPTIM, "fdrandom"))
    lz = [ln.strip() for ln in (zero / "rundir" / "output.txt").read_text().split("\n") if " ADM " in ln]
    lr = [ln.strip() for ln in (rnd / "rundir" / "output.txt").read_text().split("\n") if " ADM " in ln]
    same = [a for a, b in zip(lz, lr) if a == b]
    out = ["## FD oracle: tutorial_global_oce_optim/input_ad (option (i), Nikolay 2026-10-01)", "",
           "The forward-only `code_ad` build reads `adxx_qnet.0000000000` in GRDCHK_GETADXX (grdchk_main.F:274) and "
           "uses it only in the printed ratio (grdchk_main.F:434-437); the FD gradient comes from the +-grdchk_eps "
           "forward runs (THE_MAIN_LOOP at grdchk_main.F:359, 400). The run directory gets the file an adjoint build "
           "leaves, with zero values (`reference/grdchk_adxx.py`: tiled `adxx_qnet.0000000000.<iG>.<jG>.data/.meta`, "
           "1 record of 45x20 float64 big-endian per tile, the layout CTRL_SET_GLOBFLD_XY writes for both "
           "`xx_qnet` and `adxx_qnet`, ctrl_init_ctrlvar.F:143-151; the zero data asserted byte-equal to the "
           "run's own zero `xx_qnet.0000000000` files; meta files copied from them). Nothing else in the "
           "experiment changes (no namelist overlay).", "",
           f"Zero vs random `adxx_qnet` (job 27827478): {len(same)} of {len(lz)} `ADM` lines identical; the lines "
           "that differ are exactly the `ADM  adjoint_gradient` lines:", ""]
    out += [f"    zero:   {a}\n    random: {b}" for a, b in zip(lz, lr) if a != b]
    out += ["", "The `ADM  ref_cost_function` and `ADM  finite-diff_grad` lines of the zero run (identical in the "
            "random run):", ""] + [f"    {a}" for a in lz if "adjoint_gradient" not in a]
    out += ["", "Against `results/output_adm.txt` (checkpoint68x TAF build): admCst 16 and admFwd 16 digits "
            "(table above); the fcpertplus/fcpertminus values agree in every printed digit as well."]
    return out


def m2_invisibility_section(variants=None, milestone="M2"):
    """Invisibility verdicts of the M2 (M3) triples (reference/jaxdump/invisibility.py files next to the runs)."""
    out = [f"## {milestone}: invisibility of the jaxdump shim (plain vs dumps off vs dumps on)", "",
           "| variant | job | verdict file | verdict |", "|---|---|---|---|"]
    for exp, inp, code in (rr.M2_VARIANTS if variants is None else variants):
        j = rr.M2_TRIPLE.get((exp, inp)) or rr.M3_TRIPLE.get((exp, inp)) or rr.M4_TRIPLE[(exp, inp)]
        f = rr.invisibility_file(exp, inp)
        text = f.read_text() if f.is_file() else ""
        lines = [ln for ln in text.split("\n") if ln.startswith(("INVISIBLE", "VISIBLE"))]
        verdict = "VISIBLE" if any(ln.startswith("VISIBLE") for ln in lines) else "INVISIBLE" if lines else "MISSING"
        ex = sorted({m for ln in lines for m in re.findall(r"(DIAGSTATS_UNSET_REGIONS [1-9]\d*)", ln)})
        note = f" ({', '.join(ex)})" if ex else ""
        out.append(f"| {_variant_label(exp, inp)} | {j} | {f.name} | {verdict}{note} |")
    if milestone != "M2":
        return out + ["", "Exemptions as in Task 4 and M2 (build stamps, timers, communication counters with the probe "
                      f"on, netCDF build stamps); no new exemption for {milestone}."]
    out += ["", "Exemptions as in Task 4 (build stamps, timers, communication counters with the probe on, netCDF build "
            "stamps), plus DIAGSTATS_UNSET_REGIONS (`reference/jaxdump/invisibility.py`): global_ocean.cs32x15/input "
            "writes the statistics-diagnostics file dynStDiag (mnc) with statGlob(.,.,j) of all 11 regions, but only "
            "region 0 is computed (no stat_region in data.diagnostics); regions 1-10 hold uninitialised values of a "
            "local array (diagstats_output.F:77-84, diagstats_mnc_out.F:255-257, 298-301), which differ between the "
            "plain and the instrumented binary. Region 0 and every other byte are identical."]
    return out


def m2_fd_section(fd=None, milestone="M2"):
    """Zero vs random adxx runs of the M2 (M4) code_ad variants: the FD lines must not depend on the adxx file."""
    out = [f"## {milestone}: FD oracle of the forward-only code_ad variants (option (i) as for optim)", "",
           "| variant | control | ADM lines identical (zero vs random) | lines that differ |", "|---|---|---|---|"]
    for (exp, inp), (job, name) in (rr.M2_FD if fd is None else fd).items():
        lz, lr = ([ln.strip() for ln in (rr.run_top(rr.find_run(exp, inp, k)) / "rundir" / "output.txt").read_text()
                   .split("\n") if " ADM " in ln] for k in ("fdzero", "fdrandom"))
        diff = sorted({a.split("ADM", 1)[1].split()[0] for a, b in zip(lz, lr) if a != b})
        out.append(f"| {_variant_label(exp, inp)} | {name} | {sum(a == b for a, b in zip(lz, lr))} of {len(lz)} "
                   f"| {' '.join(diff) or '-'} |")
    return out


def m2_output_off_section():
    """Output requests off in the M2 variants (lane A session 8): model lines and MDS pickups vs the plain run."""
    out = ["## M2: output requests off (diagnostics, mnc are not ported; brainstorm section 3)", "",
           "Overlay runs `job<N>-diagoff` (data.pkg useDiagnostics=.FALSE.) and `job<N>-mncoff` (useMNC=.FALSE.) of "
           "every M2 variant whose plain run says `pkg/diagnostics` or `pkg/mnc compiled and used`; compared with "
           "the plain (yardstick) run by `reference_runs.output_request_problems`: the STDOUT model lines (%MON incl. "
           "trcstat, %SBO, cg2d, cost fc and objf terms, ADM) line for line, and every MDS pickup (rundir/pickup*) "
           "both runs wrote byte for byte. Gate: `test_m2_oracle.py::test_output_request_runs_change_no_model_number` "
           "(M1 runs of job 27827363 included).", "",
           "| variant | overlay | run | model lines | MDS pickups compared | result |", "|---|---|---|---:|---:|---|"]
    for (exp, inp), (labs, job) in rr.OUTPUT_OFF_M2.items():
        for lab in labs:
            run = rr.find_run(exp, inp, lab)
            probs, n, common = rr.output_request_problems(rr.run_top(rr.find_run(exp, inp, "yardstick")),
                                                          rr.run_top(run))
            out.append(f"| {_variant_label(exp, inp)} | {lab} | {run['run_id']} | {n} | {len(common)} | "
                       f"{'identical' if not probs else 'DIFFERENT: ' + '; '.join(probs)} |")
    return out


def m2_adm_monitor_section():
    """The TAF adjoint monitor lines (`%MON ad_*`) of results/output_adm*.txt for every M2 adjoint variant: the
    reference the JAX adjoint monitor will be measured against (lane A session 7)."""
    out = ["## M2: TAF adjoint monitor lines in `results/output_adm*.txt` (reference for the JAX adjoint monitor)", "",
           "Upstream's adjoint builds print one `%MON ad_*` block per iteration of the reverse sweep (MONITOR in "
           "adjoint mode, adMonitorFreq; `ad_time_tsnumber` starts each block), from nIter0+nTimeSteps down to "
           "nIter0. Our forward-only builds print none; these blocks are what a JAX adjoint monitor reproduces. "
           "Fields: group (statistics); `ad_time_secondsf` is in every block as well. *Check list* = the groups "
           "testreport's adm check list reads (`tools/testreport_jax.py`, the variant's listVar; testreport compares "
           "them over all blocks). Parsed by `reference_runs.adm_monitor_blocks` from the files at 63cdc0b.", "",
           "| variant | results file | blocks | ad_time_tsnumber (printed order) | records per step | fields per block "
           "| all-zero groups | groups on testreport's check list |", "|---|---|---:|---|---|---|---|---|"]
    for exp, inp, code in rr.M2_VARIANTS:
        if code != "code_ad":
            continue
        kind = trj.kind_of_variant(inp)
        ref = rr.paths.UPSTREAM / "verification" / exp / "results" / trj.reference_name(inp, kind)
        s = rr.adm_monitor_summary(rr.adm_monitor_blocks(trj.read_lines(ref)))
        files = trj.resolve_checklists(rr.paths.UPSTREAM / "verification" / exp, inp, kind)
        run = trj.testoutput_run([], trj.read_lines(ref), kind, {k: q.read_text() for k, q in files.items()})
        pats = [v.pattern for v in run.variables]
        listed = [g for g, _ in s["fields"] if any(pt in g + "_" + st for pt in pats for st in rr.AD_STATS)]
        ts = s["tsnumbers"]
        tss = f"{ts[0]}..{ts[-1]}" if ts and ts == list(range(ts[0], ts[-1] - 1, -1)) else " ".join(map(str, ts))
        flds = "; ".join(f"{g.replace('ad_dynstat_', '')} ({' '.join(st)})" for g, st in s["fields"])
        if not s["same_fields"]:
            flds += " (NOT the same fields in every block)"
        out.append(f"| {_variant_label(exp, inp)} | {ref.name} | {len(ts)} | {tss} | "
                   f"{' '.join(map(str, s['records_per_step']))} | {flds} | "
                   f"{' '.join(g.replace('ad_dynstat_', '') for g in s['all_zero_groups']) or '-'} | "
                   f"{' '.join(g.replace('ad_dynstat_', '') for g in listed) or '-'} |")
    out += ["", "Group names without the `ad_dynstat_` prefix (`ad_forcing_*`, `ad_trcstat_*` written in full)."]
    return out


def m2_minimal_section():
    """adjustment.cs-32x32x1/input_min (code_min): what its run prints and what is compared."""
    out = ["## M2: adjustment.cs-32x32x1 minimal case (`code_min`, `input_min`)", ""]
    for exp, inp, code in rr.M2_MIN:
        run = rr.find_run(exp, inp, "minimal")
        top = rr.run_top(run) / "rundir"
        lines = (top / "output.txt").read_text().split("\n")
        code_run = rr.run_top(rr.find_run(exp, "input", "yardstick")) / "rundir"
        a = (top / "w2_tile_topology.0000.log").read_text().split("\n")
        b = (code_run / "w2_tile_topology.0000.log").read_text().split("\n")
        diff = [i for i, (x, y) in enumerate(zip(a, b)) if x != y]
        i, n = (diff[0], len(b) - len(a) + 1) if diff else (None, 0)
        rest = "every other line equal" if diff and a[:i] + a[i + 1:] == b[:i] + b[i + n:] else \
            "OTHER LINES DIFFER TOO"
        out += [f"Run `{run['run_id']}` (binary `{rr.bin_name(exp, code, run['build'])}`, genmake2 "
                "`-standarddirs eesupp`): EEBOOT and the W2 topology set-up only; `code_min/main.F` skips "
                "THE_MODEL_MAIN, so the STDOUT has no `%MON` line and there is no `results/` file (testreport does not "
                f"build code_min). STDOUT {len(lines) - 1} lines, normal end. No yardstick digits exist; the reference "
                "is our own oracle.", "",
                f"W2 topology log vs the `code` build's (`{rr.find_run(exp, 'input', 'yardstick')['run_id']}`, same "
                f"SIZE.h, no data.exch2 in either): {len(a)} vs {len(b)} lines; identical except from line "
                f"{diff[0] + 1 if diff else '-'}: `code/W2_OPTIONS.h` defines W2_CUMSUM_USE_MATRIX and code_min has "
                "no W2_OPTIONS.h (pkg/exch2's leaves it undefined), so W2_SET_MAP_CUMSUM prints `done (skip Tile Matrix "
                "setting)` (1 line) instead of the 48-tile matrix "
                f"({n} lines); {rest}.", "",
                "Proposal for Nikolay: the acceptance of `input_min` (plan Task 25 asks \"≥ yardstick and ≥ 13 digits\") "
                "is the W2 set-up: the JAX W2 log and the STDOUT W2 lines equal this run's (no digits to measure)."]
    return out


def render_yardstick():
    lines = ["# Yardstick: digits of our Fortran oracle vs `results/` (plan Task 3b)", "", GEN, "",
             "Digits are testreport's (`tools/testreport_jax.py`, a literal port of `verification/testreport`'s "
             "comparison): 16 = every printed digit equal, 22 = every value zero in both files, `--` = no comparison "
             "(fewer than 2 lines, or line counts differ). Our oracle: gfortran 11.2.0 build of master 63cdc0b with "
             "testreport's options (`reference/README.md`); runs in `docs/REFERENCE_RUNS.md`. The variables are "
             "testreport's check list of each variant (`tr_checklist`, else the default list); testreport decides on "
             "the first one only, acceptance (plan Overview) reads every one.", ""]
    lines += yardstick_section() + [""] + PROPOSALS.split("\n") + invariance_section() + [""] + repeat_section()
    lines += [""] + fd_section()
    lines += [""] + yardstick_section(rr.M2_VARIANTS, "## M2 yardstick: our oracle's STDOUT vs `results/` (lane A "
                                      "session 6)")
    lines += [""] + M2_PROPOSALS.split("\n") + m2_invisibility_section() + [""] + m2_fd_section()
    lines += [""] + m2_adm_monitor_section() + [""] + m2_minimal_section() + [""] + m2_output_off_section()
    lines += [""] + yardstick_section(rr.M3_VARIANTS, "## M3 yardstick: our oracle's STDOUT vs `results/` (lane A "
                                      "session 9)")
    lines += [""] + M3_PROPOSALS.split("\n") + m2_invisibility_section(rr.M3_VARIANTS, "M3")
    lines += [""] + yardstick_section(rr.M4_VARIANTS, "## M4 yardstick: our oracle's STDOUT vs `results/` (lane A "
                                      "session 11)")
    lines += [""] + M4_PROPOSALS.split("\n") + below10_section(rr.M4_VARIANTS, "M4") + [""]
    lines += m2_invisibility_section(rr.M4_VARIANTS, "M4") + [""] + m2_fd_section(rr.M4_FD, "M4")
    return "\n".join(lines).rstrip("\n") + "\n"


def render_reference_runs():
    lock = rr.read_lock()
    lines = ["# Reference runs of the Fortran oracle (plan Task 3b)", "", GEN, "",
             "Every oracle run the project relies on. Run directory: `$MJX_REFERENCE_RUNS/<experiment>/<input dir>/"
             "<run id>/` (`rundir/output.txt` is the STDOUT). Each run is checked by `reference/reference_runs.py "
             "--check` and `scripts/tests/test_reference_runs.py`: MANIFEST.json names the binary below, whose "
             "sha256 file, MANIFEST entry and file agree; exit code 0; the files recorded in "
             "`reference/reference_runs.lock.json` (STDOUT of every run, copied adxx files, dump listings) have the "
             "recorded sha256. Nothing here is deleted or overwritten.", "", "## Binaries", "",
             "| binary (`$MJX_REFERENCE/bin/`) | sha256 | build job | what |", "|---|---|---|---|"]
    seen = {}
    for run in rr.RUNS:
        key = rr.run_key(run)
        b = lock[key]["binary"]
        seen.setdefault(b, (lock[key]["binary_sha256"], run["build"]))
    for b, (h, build) in sorted(seen.items()):
        lines.append(f"| {b} | `{h}` | {rr.BUILDS[build][1]} | {rr.BUILDS[build][2]} |")
    lines += ["", "## Runs", "", "| variant | run id | binary | job | purpose | STDOUT sha256 (first 16) |",
              "|---|---|---|---|---|---|"]
    for run in rr.RUNS:
        key = rr.run_key(run)
        rec = lock[key]
        lines.append(f"| {run['exp']}/{run['input']} | {run['run_id']} | {rec['binary']} | {run['job']} | "
                     f"{run['purpose']}{'' if run['ends_normally'] else ' (ends in the grdchk STOP: no adxx file)'} | "
                     f"`{rec['sha256']['rundir/output.txt'][:16]}` |")
    lines += ["", "## Adjoint control files of the FD runs (`reference/grdchk_adxx.py`, option (i))", "",
              "| run | file | sha256 | source |", "|---|---|---|---|"]
    for run in rr.RUNS:
        if run["kind"] not in ("fdzero", "fdrandom"):
            continue
        man = json.loads((rr.run_top(run) / "MANIFEST.json").read_text())
        for c in man["copies"]:
            lines.append(f"| {run['run_id']} | {c['name']} | `{c['sha256']}` | {Path(c['source']).parent.name} |")
    lines += ["", "## Gate fixtures (planted inputs and namelist overlays; never a yardstick or plain oracle run)", "",
              "| run | overlays (MANIFEST.json, OVERLAY.txt) | copied file | sha256 | source |", "|---|---|---|---|---|"]
    for run in rr.RUNS:
        if run["kind"] not in rr.FIXTURE_KINDS:
            continue
        man = json.loads((rr.run_top(run) / "MANIFEST.json").read_text())
        ov = "; ".join(f"{o['file']} &{o['group']} {o['key']}={o['value']}" for o in man.get("overlays") or [])
        for c in man.get("copies") or [{"name": "-", "sha256": "-", "source": "-/-"}]:
            src = Path(c["source"]).parts
            # a file copied from another run directory: name that run (<run id>/verification/<exp>/<run dir>/<file>)
            src = src[src.index("verification") - 1] if "verification" in src else src[-2]
            lines.append(f"| {run['run_id']} | {ov} | {c['name']} | `{c['sha256']}` | {src} |")
    lines += ["", "Generated (login node, seconds) from the forward-only run job27826998-plain with "
              "`reference/grdchk_adxx.py <run> $MJX_REFERENCE/grdchk_adxx/32f1043-zero` and `... "
              "32f1043-random20261001 --random 20261001` (SHA256SUMS and PROVENANCE.txt next to them).", "",
              "M2 code_ad variants (lane A session 6): `reference/grdchk_adxx.py <job27832229-plain run> "
              "$MJX_REFERENCE/grdchk_adxx/30b10ae-<exp>-<input>-zero --name <control>` and `... -random20261001 "
              "--random 20261001`; global_ocean.90x40x15/input_ad* run with useSingleCpuIO=.TRUE. (one global file). "
              "Session 7: `reference/grdchk_adxx.py <job27832624-plain run> $MJX_REFERENCE/grdchk_adxx/"
              "d117407-global_ocean.cs32x15-input_ad-zero --name xx_theta` and `... -random20261001 --random "
              "20261001` (12 tiled files, one per cube tile).", "",
              "Planted first-guess controls of the global_ocean.90x40x15 code_ad family (lane A session 8, gate "
              "fixtures `job27833840-ctrlxx`): `reference/grdchk_adxx.py <job27832229-plain run> "
              "$MJX_REFERENCE/ctrl_planted/0542f7a-<exp>-<input>-<name>-seed20261001 --name <name> --prefix '' "
              "--random 20261001 --amp A` (A: xx_theta 0.5, xx_kapgm and xx_kapredi 100, xx_bottomdrag 2e-4; one "
              "global file each).",
              "",
              "## Runs that exist but are not used", "",
              "- `job27826794-{plain,jdoff,jdon}` (all variants but optim): made with the superseded f4448f8 jaxdump "
              "binaries (V-group overrun); deletion candidates (lane A handoff).",
              "- `tutorial_global_oce_optim/input_ad/job27826873-{plain,jdoff,jdon}`: valid runs of the same binaries "
              "as job27826998 (their invisibility verdict was wrong through a checker bug fixed in f245016); "
              "job27826998 is the registered one.",
              "- `tutorial_barotropic_gyre/input/job27826032` is registered as the repeat run of that variant "
              "(lane D's job 27826871 did not run the barotropic gyre).",
              "- `tutorial_global_oce_optim/input_ad/job27829092-ctrlxx` (CTRL lane): failed run (exit 2 while "
              "unpacking the controls, overlay doInitXX only); superseded by job27829159-ctrlxx; deletion candidate "
              "(main session).",
              "- `global_ocean.cs32x15/input.in_p/job27832228-{plain,jdoff,jdon}` and its invisibility-job27832228.txt: "
              "the run directories lacked prepare_run's sibling inputs (../input.icedyn, ../input.seaice; the model "
              "stopped reading data.exf); superseded by job27832348 after the make_rundir fix 30695ea; deletion "
              "candidates (lane A handoff).",
              "- `global_ocean.cs32x15/input/invisibility-job27832228.txt`: the job's own verdict (VISIBLE: the "
              "uninitialised regions of dynStDiag); the registered verdict is invisibility-job27832228-r30b10ae.txt."]
    return "\n".join(lines) + "\n"


def render():
    return {"YARDSTICK.md": render_yardstick(), "REFERENCE_RUNS.md": render_reference_runs()}
